//! ProjectB top-level Rust crate (optional) that re-exports common types
//! and (optionally) includes protobufs compiled by `build.rs`.
//
// To use this as a crate, add a Cargo.toml in the repository root and list
// this directory as the package root (or move these files into a proper crate).

#![forbid(unsafe_code)]
#![deny(clippy::all)]

pub mod types;

pub use types::{Mode, Envelope, MonoNs, WallMs};

/// Protobuf modules compiled by `build.rs` (feature-gated).
/// Enable with `--features with_protos` in this crate.
#[cfg(feature = "with_protos")]
pub mod pb {
    // Generated by prostbuild in build.rs
    include!(concat!(env!("OUT_DIR"), "/projectb.shared.rs"));
}